sudo: false
language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi
  - export JOBS=max
os:
  - linux
node_js:
  - "8"
script:
  - npx macleod exec npm i && npx macleod exec npm t
